from pathlib import Path
import config_v2 as v2

PROJECT_ROOT=Path(__file__).resolve().parent
PROCESSED_DIR=v2.PROCESSED_DIR
RESULTS_V2_DIR=v2.RESULTS_DIR
RESULTS_DIR=PROJECT_ROOT/"results_v25"
FIGURES_DIR=PROJECT_ROOT/"figures_v25"
CACHE_DIR=PROJECT_ROOT/"cache_v25"
BATTERIES=v2.BATTERIES
HORIZONS=v2.HORIZONS
REPORT_HORIZONS=[1,8,24,32,48,64]
HFS=v2.HFS
FEATURE_GROUPS=v2.FEATURE_GROUPS
HISTORY_LENGTH=32
RECENT_LENGTH=8
PRIMARY_ALPHA=v2.PRIMARY_ALPHA
PERMUTATIONS=1000
MIN_STATE_N=30
RANDOM_SEED=42
# Fixed, predeclared reference avoids using a held-out battery's future endpoint.
CYCLE_POSITION_REFERENCE=1000

